services:
  todo-database:
    image: mysql:8.0
    container_name: todo-database
    ports:
      - "3309:3306"
    volumes:
      - todo_db:/var/lib/mysql
    restart: always
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: todoapp-db-pass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo-dgebwgkthv

volumes:
  todo_db:
