production:
  dialect: mysql
  datasource: todo:todo-dgebwgkthv@(127.0.0.1:3309)/todo_db?parseTime=true
  dir: ./repository/mysql/migrations


# datasource schema
# user:password@(host:port)/dbname?param...
